config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/tests', controller: 'tests', action: 'index', as: 'tests'
  patch '/answer/:id', controller: 'tasks', action: 'answer', as: 'answer'

  post '/attempt/:test_id', controller: 'tests', action: 'start', as: 'start_attempt'
  get '/attempt/:id', controller: 'tests', action: 'next_question', as: 'next_question_attempt'

  scope :reports, controller: 'reports', as: 'reports' do
    get 'student'
    get 'test/:test_id', action: 'test', as: 'test'
  end

  scope :teacher, as: 'teacher' do
    scope :reports, controller: 'reports', as: 'reports' do
      get 'student/:id', action: 'student', as: 'student'
      get 'student/:id/test/:test_id', action: 'test', as: 'test'
    end
  end

  namespace :teacher do
    resources :tests, shallow: true, except: %i[show]
    resources :students, shallow: true, except: %i[show]
    resources :groups, shallow: true, except: %i[show]

    resources :questions do
      resources :parameters, only: [] do
        get :edit, on: :collection
        patch :update, on: :collection
      end
    end
  end
end

app/models/student.rb
# frozen_string_literal: true

class Student < User
  validates :first_name, :last_name, presence: true

  belongs_to :group
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < User
  has_many :questions, foreign_key: 'author_id', inverse_of: 'author', dependent: :destroy
end

app/controllers/teacher/base_controller.rb
# frozen_string_literal: true

# :reek:MissingSafeMethod { exclude: [ teacher_required! ] }
class Teacher::BaseController < ApplicationController
  # layout 'teacher'

  before_action :teacher_required!

  def teacher_required!
    redirect_to root_path, alert: t('teacher.base.restricted') unless current_user&.teacher?
  end
end

app/controllers/teacher/groups_controller.rb
# frozen_string_literal: true

class Teacher::GroupsController < Teacher::BaseController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to teacher_groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to teacher_groups_path
    else
      render :edit
    end
  end

  def destroy
    Group.find_by(id: params[:id])&.destroy

    redirect_to teacher_groups_path
  end

  private

  def group_params
    params.require(:group)
          .permit(:name, :year)
  end
end

app/controllers/teacher/parameters_controller.rb
# frozen_string_literal: true

# NB: This controller is used for bulk parameters processing

class Teacher::ParametersController < Teacher::BaseController
  before_action :find_question

  def edit; end

  def update
    flash.now[:notice] = t('.successful') if @question.update(parameters_params)
    render :edit
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def parameters_params
    params.require(:question)
          .permit(parameters_attributes: %i[id minimum maximum step unit])
  end
end

app/controllers/teacher/questions_controller.rb
# frozen_string_literal: true

class Teacher::QuestionsController < Teacher::BaseController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save && @question.create_parameters
      redirect_to edit_teacher_question_parameters_path(@question), notice: t('.successful')
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.attributes = question_params
    redirect_path = update_redirect_path

    if @question.save
      redirect_to redirect_path, notice: t('.successful')
    else
      render :edit
    end
  end

  def index
    @questions = Question.includes(:test).all.page(params[:page]).per(10)
  end

  def show
    @question = Question.find(params[:id])
    @task = Task.new_from(@question)
  end

  def destroy
    Question.find_by(id: params[:id])&.destroy

    redirect_to teacher_questions_path
  end

  private

  # NB: call before @question.save
  def update_redirect_path
    if @question.formula_text_changed?
      edit_teacher_question_parameters_path(@question)
    else
      teacher_questions_path
    end
  end

  def question_params
    params.require(:question)
          .permit(:text, :comment, :formula_text,
                  :precision, :answer_unit, :completion_time,
                  :scheme, :test_id)
          .merge(author_id: current_user.id)
  end
end

app/controllers/teacher/students_controller.rb
# frozen_string_literal: true

class Teacher::StudentsController < Teacher::BaseController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to teacher_students_path, notice: t('.successful')
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  # :reek:DuplicateMethodCall
  def update
    @student = Student.find(params[:id])
    params[:student].delete(:password) if params[:student][:password].blank?

    if @student.update(student_params)
      redirect_to teacher_students_path, notice: t('.successful')
    else
      render :edit
    end
  end

  def destroy
    Student.find_by(id: params[:id])&.destroy

    redirect_to teacher_students_path
  end

  private

  def student_params
    params.require(:student)
          .permit(:email, :password,
                  :group_id,
                  :first_name, :middle_name, :last_name)
  end
end

app/controllers/teacher/tests_controller.rb
# frozen_string_literal: true

class Teacher::TestsController < Teacher::BaseController
  def index
    @tests = Test.includes(:questions).all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to teacher_tests_path
    else
      render :new
    end
  end

  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to teacher_tests_path
    else
      render :edit
    end
  end

  def destroy
    Test.find_by(id: params[:id])&.destroy

    redirect_to teacher_tests_path
  end

  private

  def test_params
    params.require(:test)
          .permit(:name, :target_score)
  end
end

app/views/teacher/students/_form.html.slim
= render 'shared/errors', resource: @student

= form_with model: [:teacher, @student] do |f|
  .form-group
    = f.label :email, class: 'form-label'
    = f.text_field :email, class: 'form-input'

  .form-group
    = f.label :password, class: 'form-label'
    em.block.mb-1
      | (оставьте пустым, если не требует изменения)
    = f.text_field :password, class: 'form-input'

  .form-group
    = f.label :last_name, class: 'form-label'
    = f.text_field :last_name, class: 'form-input'

  .form-group
    = f.label :first_name, class: 'form-label'
    = f.text_field :first_name, class: 'form-input'

  .form-group
    = f.label :middle_name, class: 'form-label'
    em.block.mb-1
      | (при наличии)
    = f.text_field :middle_name, class: 'form-input'

  .form-group
    = f.label :group, class: 'form-label'
    = f.collection_select :group_id, Group.all, :id, :to_s, {}, class: 'form-input'

  .form-actions
    = f.submit 'Сохранить', class: 'button'

app/views/teacher/students/edit.html.slim
= render 'form'

app/views/teacher/students/index.html.slim
.table-wrapper
  table.table
    thead.table-head
      th.table-header
        | ID
      th.table-header
        = User.human_attribute_name(:email)
      th.table-header
        = User.human_attribute_name(:last_name)
      th.table-header
        = User.human_attribute_name(:first_name)
      th.table-header
        = User.human_attribute_name(:middle_name)
      th.table-header
        = User.human_attribute_name(:group)
      th.table-header
        | Действия

    tbody.table-body
    - @students.each do |student|
      tr.table-row class="student-#{student.id}"
        td.table-cell
          = student.id
        td.table-cell
          = student.email
        td.table-cell
          = student.last_name
        td.table-cell
          = student.first_name
        td.table-cell
          = student.middle_name
        td.table-cell
          = student.group
        td.table-cell.space-x-4
          = link_to 'Статистика', teacher_reports_student_path(student), class: 'link'
          = link_to 'Редактировать', edit_teacher_student_path(student), class: 'link'
          = link_to 'Удалить', teacher_student_path(student), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'link'

= link_to 'Создать нового', new_teacher_student_path, class: 'button'

app/views/teacher/students/new.html.slim
= render 'form'