config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/tests', controller: 'tests', action: 'index', as: 'tests'
  patch '/answer/:id', controller: 'tasks', action: 'answer', as: 'answer'

  post '/attempt/:test_id', controller: 'tests', action: 'start', as: 'start_attempt'
  get '/attempt/:id', controller: 'tests', action: 'next_question', as: 'next_question_attempt'

  scope :reports, controller: 'reports', as: 'reports' do
    get 'student'
    get 'test/:test_id', action: 'test', as: 'test'
  end

  scope :teacher, as: 'teacher' do
    scope :reports, controller: 'reports', as: 'reports' do
      get 'student/:id', action: 'student', as: 'student'
      get 'student/:id/test/:test_id', action: 'test', as: 'test'
    end
  end

  namespace :teacher do
    resources :tests, shallow: true, except: %i[show]
    resources :students, shallow: true, except: %i[show]
    resources :groups, shallow: true, except: %i[show]

    resources :questions do
      resources :parameters, only: [] do
        get :edit, on: :collection
        patch :update, on: :collection
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Authorable

  validates :text, :formula, :formula_text, :precision, presence: true
  validates :scheme, blob: { content_type: :image, size_range: 1..1.megabytes }
  validates :precision, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  validates :completion_time, allow_nil: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  validate :validates_formula_text

  belongs_to :test

  has_many :parameters, dependent: :destroy
  has_many :tasks, dependent: :nullify

  has_one_attached :scheme

  accepts_nested_attributes_for :parameters

  before_validation :set_formula, if: :formula_text_changed?
  before_update :remove_unused_parameters, :add_new_parameters, if: :formula_changed?

  def create_parameters
    formula['dependencies'].each do |name|
      parameters.create(name: name, **Formula::Parameter.call(name))
    end
  end

  private

  def validates_formula_text
    return unless formula_text
    return if Formula::Validator.call(formula_text)

    errors.add :formula_text, :wrong
  end

  def set_formula
    self.formula = Formula::Parser.call(formula_text)
  end

  def remove_unused_parameters
    parameters_unused = parameters.reject do |parameter|
      formula['dependencies'].include?(parameter.name)
    end

    parameters_unused.each(&:destroy)
  end

  def add_new_parameters
    parameter_names = parameters.pluck(:name)

    parameters_new = formula['dependencies'].reject do |name|
      parameter_names.include?(name)
    end

    parameters_new.each do |name|
      parameters.create(name: name, **Formula::Parameter.call(name))
    end
  end
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < User
  has_many :questions, foreign_key: 'author_id', inverse_of: 'author', dependent: :destroy
end

app/controllers/teacher/base_controller.rb
# frozen_string_literal: true

# :reek:MissingSafeMethod { exclude: [ teacher_required! ] }
class Teacher::BaseController < ApplicationController
  # layout 'teacher'

  before_action :teacher_required!

  def teacher_required!
    redirect_to root_path, alert: t('teacher.base.restricted') unless current_user&.teacher?
  end
end

app/controllers/teacher/groups_controller.rb
# frozen_string_literal: true

class Teacher::GroupsController < Teacher::BaseController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to teacher_groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to teacher_groups_path
    else
      render :edit
    end
  end

  def destroy
    Group.find_by(id: params[:id])&.destroy

    redirect_to teacher_groups_path
  end

  private

  def group_params
    params.require(:group)
          .permit(:name, :year)
  end
end

app/controllers/teacher/parameters_controller.rb
# frozen_string_literal: true

# NB: This controller is used for bulk parameters processing

class Teacher::ParametersController < Teacher::BaseController
  before_action :find_question

  def edit; end

  def update
    flash.now[:notice] = t('.successful') if @question.update(parameters_params)
    render :edit
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def parameters_params
    params.require(:question)
          .permit(parameters_attributes: %i[id minimum maximum step unit])
  end
end

app/controllers/teacher/questions_controller.rb
# frozen_string_literal: true

class Teacher::QuestionsController < Teacher::BaseController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save && @question.create_parameters
      redirect_to edit_teacher_question_parameters_path(@question), notice: t('.successful')
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.attributes = question_params
    redirect_path = update_redirect_path

    if @question.save
      redirect_to redirect_path, notice: t('.successful')
    else
      render :edit
    end
  end

  def index
    @questions = Question.includes(:test).all.page(params[:page]).per(10)
  end

  def show
    @question = Question.find(params[:id])
    @task = Task.new_from(@question)
  end

  def destroy
    Question.find_by(id: params[:id])&.destroy

    redirect_to teacher_questions_path
  end

  private

  # NB: call before @question.save
  def update_redirect_path
    if @question.formula_text_changed?
      edit_teacher_question_parameters_path(@question)
    else
      teacher_questions_path
    end
  end

  def question_params
    params.require(:question)
          .permit(:text, :comment, :formula_text,
                  :precision, :answer_unit, :completion_time,
                  :scheme, :test_id)
          .merge(author_id: current_user.id)
  end
end

app/controllers/teacher/students_controller.rb
# frozen_string_literal: true

class Teacher::StudentsController < Teacher::BaseController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to teacher_students_path, notice: t('.successful')
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  # :reek:DuplicateMethodCall
  def update
    @student = Student.find(params[:id])
    params[:student].delete(:password) if params[:student][:password].blank?

    if @student.update(student_params)
      redirect_to teacher_students_path, notice: t('.successful')
    else
      render :edit
    end
  end

  def destroy
    Student.find_by(id: params[:id])&.destroy

    redirect_to teacher_students_path
  end

  private

  def student_params
    params.require(:student)
          .permit(:email, :password,
                  :group_id,
                  :first_name, :middle_name, :last_name)
  end
end

app/controllers/teacher/tests_controller.rb
# frozen_string_literal: true

class Teacher::TestsController < Teacher::BaseController
  def index
    @tests = Test.includes(:questions).all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to teacher_tests_path
    else
      render :new
    end
  end

  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to teacher_tests_path
    else
      render :edit
    end
  end

  def destroy
    Test.find_by(id: params[:id])&.destroy

    redirect_to teacher_tests_path
  end

  private

  def test_params
    params.require(:test)
          .permit(:name, :target_score)
  end
end

app/views/teacher/questions/_form.html.slim
= form_with model: [:teacher, @question] do |f|
  .form-group
    = f.label :test_id, class: 'form-label'
    = f.collection_select :test_id, Test.all, :id, :name, {}, class: 'form-input'

  .form-group
    = f.label :text, class: 'form-label'
    = f.text_area :text, class: 'form-input'

  .form-group
    = f.label :comment, class: 'form-label'
    = f.text_area :comment, class: 'form-input'

  .form-group
    = f.label :answer_unit, class: 'form-label'
    = f.text_field :answer_unit, class: 'form-input'

  .form-group
    = f.label :precision, class: 'form-label'
    = f.number_field :precision, in: 0..10, step: 1, class: 'form-input'

  .form-group
    = f.label :completion_time, class: 'form-label'
    = f.number_field :completion_time, in: 0..3600, step: 1, class: 'form-input'

  .form-group
    = f.label :formula_text, class: 'form-label'
    = f.text_area :formula_text, readonly: @with_parameters, class: "form-input #{'read-only' if @with_parameters}"

  .form-group
    = f.label :scheme, class: 'form-label'
    = f.file_field :scheme

  .form-actions
    = f.submit 'Сохранить вопрос', class: 'button'

app/views/teacher/questions/_task.html.slim
.w-max.p-2.md:px-6.md:py-3.border.rounded-lg
  .py-2
    p.italic Аргументы
    - @question.parameters.each do |parameter|
      p = "#{parameter.name} = #{@task.arguments[parameter.name]} #{parameter.unit}"

  .py-2
    p.italic
      | Ответ (знаков после запятой - #{@question.precision}):
    p = "#{@task.answer} #{@question.answer_unit}"

  .py-2
    = link_to 'Сгенерировать новый', teacher_question_path(@question), class: 'button'

app/views/teacher/questions/edit.html.slim
.question-errors
  = render 'shared/errors', resource: @question

.question
  = render 'form'

.mt-4
  = link_to 'Изменить параметры формулы', edit_teacher_question_parameters_path(@question), class: 'link'

app/views/teacher/questions/index.html.slim
= paginate @questions

.table-wrapper
  table.table
    thead.table-head
      th.table-header
        | ID
      th.table-header
        = Question.human_attribute_name(:text)
      th.table-header
        = Question.human_attribute_name(:test)
      th.table-header
        | Действия

    tbody.table-body
    - @questions.each do |question|
      tr
        td.table-cell
          = question.id
        td.table-cell
          = link_to truncate(question.text, length: 80), teacher_question_path(question), class: 'link'
        td.table-cell
          = question.test.name
        td.table-cell.space-x-4
          = link_to 'Редактировать', edit_teacher_question_path(question), class: 'link'
          = link_to 'Удалить', teacher_question_path(question), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'link'

= link_to 'Создать новый', new_teacher_question_path, class: 'button'

app/views/teacher/questions/new.html.slim
.question-errors
  = render 'shared/errors', resource: @question

.question
  = render 'form'

app/views/teacher/questions/show.html.slim
.py-2
  p.italic = Question.human_attribute_name('text')
  .question-text = simple_format @question.text

- if @question.comment.present?
  .py-2
    p.italic = Question.human_attribute_name('comment')
    .question-comment = simple_format @question.comment

.py-2
  p.italic = Question.human_attribute_name('completion_time')
  p = t('plural.seconds', count: @question.completion_time)

.py-2
  p.italic = Question.human_attribute_name('formula_text')
  .formula_text = simple_format @question.formula_text

.flex.flex-col.md:flex-row
  .question-example.py-2
    p.italic Пример задания
    = render partial: 'task'

  - if @question.scheme.attached?
    .py-2.md:ml-4
      p.italic = Question.human_attribute_name('scheme')
      = image_tag @question.scheme, class: 'question-scheme'

.mt-4
  = link_to 'Изменить параметры формулы', edit_teacher_question_parameters_path(@question), class: 'link'