config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/tests', controller: 'tests', action: 'index', as: 'tests'
  patch '/answer/:id', controller: 'tasks', action: 'answer', as: 'answer'

  post '/attempt/:test_id', controller: 'tests', action: 'start', as: 'start_attempt'
  get '/attempt/:id', controller: 'tests', action: 'next_question', as: 'next_question_attempt'

  scope :reports, controller: 'reports', as: 'reports' do
    get 'student'
    get 'test/:test_id', action: 'test', as: 'test'
  end

  scope :teacher, as: 'teacher' do
    scope :reports, controller: 'reports', as: 'reports' do
      get 'student/:id', action: 'student', as: 'student'
      get 'student/:id/test/:test_id', action: 'test', as: 'test'
    end
  end

  namespace :teacher do
    resources :tests, shallow: true, except: %i[show]
    resources :students, shallow: true, except: %i[show]
    resources :groups, shallow: true, except: %i[show]

    resources :questions do
      resources :parameters, only: [] do
        get :edit, on: :collection
        patch :update, on: :collection
      end
    end
  end
end

app/models/parameter.rb
# frozen_string_literal: true

class Parameter < ApplicationRecord
  validate :validates_formula_dependency

  belongs_to :question

  def step?
    is_a?(StepParameter)
  end

  def enum?
    is_a?(EnumParameter)
  end

  def formula?
    is_a?(FormulaParameter)
  end

  private

  def validates_formula_dependency
    return unless question
    return if question.formula['dependencies'].include?(name)

    errors.add :name, :not_in_dependencies
  end
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < User
  has_many :questions, foreign_key: 'author_id', inverse_of: 'author', dependent: :destroy
end

app/controllers/teacher/base_controller.rb
# frozen_string_literal: true

# :reek:MissingSafeMethod { exclude: [ teacher_required! ] }
class Teacher::BaseController < ApplicationController
  # layout 'teacher'

  before_action :teacher_required!

  def teacher_required!
    redirect_to root_path, alert: t('teacher.base.restricted') unless current_user&.teacher?
  end
end

app/controllers/teacher/groups_controller.rb
# frozen_string_literal: true

class Teacher::GroupsController < Teacher::BaseController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to teacher_groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to teacher_groups_path
    else
      render :edit
    end
  end

  def destroy
    Group.find_by(id: params[:id])&.destroy

    redirect_to teacher_groups_path
  end

  private

  def group_params
    params.require(:group)
          .permit(:name, :year)
  end
end

app/controllers/teacher/parameters_controller.rb
# frozen_string_literal: true

# NB: This controller is used for bulk parameters processing

class Teacher::ParametersController < Teacher::BaseController
  before_action :find_question

  def edit; end

  def update
    flash.now[:notice] = t('.successful') if @question.update(parameters_params)
    render :edit
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def parameters_params
    params.require(:question)
          .permit(parameters_attributes: %i[id minimum maximum step unit])
  end
end

app/controllers/teacher/questions_controller.rb
# frozen_string_literal: true

class Teacher::QuestionsController < Teacher::BaseController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save && @question.create_parameters
      redirect_to edit_teacher_question_parameters_path(@question), notice: t('.successful')
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.attributes = question_params
    redirect_path = update_redirect_path

    if @question.save
      redirect_to redirect_path, notice: t('.successful')
    else
      render :edit
    end
  end

  def index
    @questions = Question.includes(:test).all.page(params[:page]).per(10)
  end

  def show
    @question = Question.find(params[:id])
    @task = Task.new_from(@question)
  end

  def destroy
    Question.find_by(id: params[:id])&.destroy

    redirect_to teacher_questions_path
  end

  private

  # NB: call before @question.save
  def update_redirect_path
    if @question.formula_text_changed?
      edit_teacher_question_parameters_path(@question)
    else
      teacher_questions_path
    end
  end

  def question_params
    params.require(:question)
          .permit(:text, :comment, :formula_text,
                  :precision, :answer_unit, :completion_time,
                  :scheme, :test_id)
          .merge(author_id: current_user.id)
  end
end

app/controllers/teacher/students_controller.rb
# frozen_string_literal: true

class Teacher::StudentsController < Teacher::BaseController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to teacher_students_path, notice: t('.successful')
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  # :reek:DuplicateMethodCall
  def update
    @student = Student.find(params[:id])
    params[:student].delete(:password) if params[:student][:password].blank?

    if @student.update(student_params)
      redirect_to teacher_students_path, notice: t('.successful')
    else
      render :edit
    end
  end

  def destroy
    Student.find_by(id: params[:id])&.destroy

    redirect_to teacher_students_path
  end

  private

  def student_params
    params.require(:student)
          .permit(:email, :password,
                  :group_id,
                  :first_name, :middle_name, :last_name)
  end
end

app/controllers/teacher/tests_controller.rb
# frozen_string_literal: true

class Teacher::TestsController < Teacher::BaseController
  def index
    @tests = Test.includes(:questions).all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to teacher_tests_path
    else
      render :new
    end
  end

  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to teacher_tests_path
    else
      render :edit
    end
  end

  def destroy
    Test.find_by(id: params[:id])&.destroy

    redirect_to teacher_tests_path
  end

  private

  def test_params
    params.require(:test)
          .permit(:name, :target_score)
  end
end

app/views/teacher/parameters/_enum_parameter.html.slim
.block.w-max.p-4.m-2.border.rounded-lg
  .form-group
    = enum_parameter.label :name, class: 'form-label'
    = enum_parameter.text_field :name, readonly: true, class: 'form-input read-only'

  .form-group
    = enum_parameter.label :variants, class: 'form-label'
    = enum_parameter.text_field :variants, readonly: true, class: 'form-input read-only'

  .form-group
    = enum_parameter.label :unit, class: 'form-label'
    = enum_parameter.text_field :unit, class: 'form-input'

app/views/teacher/parameters/_formula_parameter.html.slim
.block.w-max.p-4.m-2.border.rounded-lg
  .form-group
    = formula_parameter.label :name, class: 'form-label'
    = formula_parameter.text_field :name, readonly: true, class: 'form-input read-only'

  .form-group
    = formula_parameter.label :formula, class: 'form-label'
    = formula_parameter.text_field :formula, readonly: true, class: 'form-input read-only'

  .form-group
    = formula_parameter.label :unit, class: 'form-label'
    = formula_parameter.text_field :unit, class: 'form-input'

app/views/teacher/parameters/_step_parameter.html.slim
.block.w-max.p-4.m-2.border.rounded-lg
  .form-group
    = step_parameter.label :name, class: 'form-label'
    = step_parameter.text_field :name, readonly: true, class: 'form-input read-only'

  .form-group
    = step_parameter.label :minimum, class: 'form-label'
    = step_parameter.number_field :minimum, step: :any, class: 'form-input'

  .form-group
    = step_parameter.label :maximum, class: 'form-label'
    = step_parameter.number_field :maximum, step: :any, class: 'form-input'

  .form-group
    = step_parameter.label :step, class: 'form-label'
    = step_parameter.number_field :step, step: :any, class: 'form-input'

  .form-group
    = step_parameter.label :unit, class: 'form-label'
    = step_parameter.text_field :unit, class: 'form-input'

app/views/teacher/parameters/edit.html.slim
.block
  = render 'shared/errors', resource: @question

.block
  p.italic = Question.human_attribute_name('formula_text')
  p = simple_format @question.formula_text

= form_with model: [:teacher, @question], url: teacher_question_parameters_path(@question) do |form|
  .flex.flex-row.flex-wrap
    = form.fields_for :parameters do |parameter|
      = render partial: parameter.object.class.to_s.underscore, object: parameter

  .form-actions
    = form.submit 'Сохранить параметры', class: 'button'

.mt-4
  = link_to 'Перейти к вопросу', teacher_question_path(@question), class: 'link'